# Generated by Django 3.1.3 on 2020-11-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20201130_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tamaño',
            field=models.CharField(choices=[('g', 'Grande'), ('m', 'Mediano'), ('c', 'Chico')], default='Solo Piercing', max_length=1, verbose_name='Tamaño'),
        ),
    ]
