# Generated by Django 3.1.3 on 2020-11-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='entrada',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='salida',
        ),
        migrations.AlterField(
            model_name='turno',
            name='tamaño',
            field=models.CharField(choices=[('', 'Grande'), ('m', 'Mediano'), ('c', 'Chico')], default='Solo Piercing', max_length=1, verbose_name='Tamaño'),
        ),
    ]
