# Generated by Django 3.1.3 on 2020-12-01 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20201130_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tamaño',
            field=models.CharField(choices=[('g', 'Grande'), ('m', 'Mediano'), ('c', 'Chico')], default='Solo Piercing', max_length=1, verbose_name='Tamaño'),
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
