# Generated by Django 3.1.3 on 2021-01-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_auto_20210117_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='responsable',
        ),
    ]
